language: ruby
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
branches:
  only:
    # Always build master & Enable building pull requests.
    - master
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
script:
  - bundle exec rspec spec
  - bundle exec cucumber
