---
version: "{branch}-{build}"

clone_depth: 10

build: off

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install bundler -f
  - bundle config --local path vendor/bundle
  - bundle install

before_test:
  - ruby --version
  - gem --version
  - bundler --version

test_script:
  - bundle exec rspec spec

artifacts:
  - path: pkg\*.gem

cache:
  - vendor/bundle

environment:
  matrix:
    - ruby_version: 23
    - ruby_version: 24
    - ruby_version: 25
