name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        ruby: ["3.0", "2.7", "2.6", "2.5"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Set up Bundler
        run: gem install bundler --no-document
      - name: Install dependencies
        run: bundle install
      - name: Run test
        run: bundle exec rspec spec
      - name: Run cucumber tests
        if: matrix.os != 'windows-latest'
        run: bundle exec cucumber
